# Generated by Django 5.2.17 on 2026-08-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("razon_social", models.CharField(max_length=255)),
                ("rfc", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "regimen_fiscal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("direccion", models.TextField(blank=True, null=True)),
                ("cp", models.CharField(blank=True, max_length=255, null=True)),
                ("contacto", models.CharField(max_length=255)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("telefono", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "telefono_secundario",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("Permanente", "Permanente"),
                            ("Eventual", "Eventual"),
                            ("Unica vez", "Única vez"),
                        ],
                        default="Eventual",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "donantes",
                "ordering": ["razon_social"],
            },
        ),
    ]
