# Generated by Django 5.2.17 on 2026-08-22 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donativos", "0001_initial"),
        ("iaps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asignacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("entregado", "Entregado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha_asignacion", models.DateTimeField(blank=True, null=True)),
                (
                    "responsable_entrega",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lugar_entrega",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fecha_entrega_real", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "iap",
                    models.ForeignKey(
                        db_column="iap_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="iaps.iap",
                    ),
                ),
            ],
            options={
                "db_table": "asignaciones",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="DetalleAsignacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("estatus", models.CharField(default="pendiente", max_length=20)),
                ("fecha_entrega", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asignacion",
                    models.ForeignKey(
                        db_column="asignacion_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="distribucion.asignacion",
                    ),
                ),
                (
                    "inventario",
                    models.ForeignKey(
                        db_column="inventario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalle_asignaciones",
                        to="donativos.inventario",
                    ),
                ),
            ],
            options={
                "db_table": "detalle_asignaciones",
            },
        ),
    ]
