# Generated by Django 5.2.17 on 2026-10-07 23:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('contenido', models.TextField()),
                ('categoria', models.CharField(choices=[('noticia', 'Noticia'), ('evento', 'Evento'), ('aviso', 'Aviso')], default='noticia', max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to='avisos/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'avisos',
                'ordering': ['-created_at'],
            },
        ),
    ]
