# Generated by Django 5.2.17 on 2026-08-21 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donantes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogoProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("categoria", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "clave_sat",
                    models.CharField(
                        blank=True, default="01010101", max_length=255, null=True
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "precio_referencia",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "catalogo_productos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Donativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_donativo", models.DateField()),
                (
                    "monto_total_deducible",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "donante",
                    models.ForeignKey(
                        db_column="donante_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donativos",
                        to="donantes.donante",
                    ),
                ),
            ],
            options={
                "db_table": "donativos",
                "ordering": ["-fecha_donativo"],
            },
        ),
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria_producto", models.CharField(max_length=255)),
                ("nombre_producto", models.CharField(max_length=255)),
                ("clave_sat", models.CharField(blank=True, max_length=255, null=True)),
                ("estado", models.CharField(default="Nuevo", max_length=50)),
                ("fecha_caducidad", models.DateField(blank=True, null=True)),
                ("modalidad", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "clave_unidad",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cantidad", models.IntegerField()),
                (
                    "cantidad_actual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "precio_venta_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "precio_venta_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "precio_unitario_deducible",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "monto_deducible_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catalogo_producto",
                    models.ForeignKey(
                        blank=True,
                        db_column="catalogo_producto_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventarios",
                        to="donativos.catalogoproducto",
                    ),
                ),
                (
                    "donativo",
                    models.ForeignKey(
                        db_column="donativo_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventarios",
                        to="donativos.donativo",
                    ),
                ),
            ],
            options={
                "db_table": "inventarios",
            },
        ),
    ]
