# Generated by Django 5.2.17 on 2026-08-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmin", "Superadmin"),
                    ("admin", "Admin"),
                    ("donativos", "Donativos"),
                    ("asistencial", "Asistencial"),
                    ("editor", "Editor"),
                    ("lector", "Lector"),
                ],
                default="editor",
                max_length=20,
            ),
        ),
    ]
