# Generated by Django 5.2.17 on 2026-08-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Iap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_iap", models.CharField(max_length=255)),
                ("estatus", models.CharField(default="Activo", max_length=20)),
                ("rubro", models.CharField(blank=True, max_length=255, null=True)),
                ("actividad_asistencial", models.TextField(blank=True, null=True)),
                (
                    "clasificacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tipo_beneficiario",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("personas_beneficiadas", models.IntegerField(default=0)),
                (
                    "necesidad_primaria",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "necesidad_complementaria",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("es_certificada", models.BooleanField(default=False)),
                ("tiene_donataria_autorizada", models.BooleanField(default=False)),
                ("tiene_padron_beneficiarios", models.BooleanField(default=False)),
                ("veces_donado", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "IAP",
                "verbose_name_plural": "IAPs",
                "db_table": "iaps",
                "ordering": ["nombre_iap"],
            },
        ),
    ]
