# Generated by Django 5.2.17 on 2026-08-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iaps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iap",
            name="estatus",
            field=models.CharField(default="Activa", max_length=20),
        ),
    ]
